module.exports = require('./framework');

// Included middleware
module.exports.ResponseTime = require("./responsetime").ResponseTime;
module.exports.ErrorHandler = require("./errorhandler").ErrorHandler;
module.exports.StaticFile = require("./staticfile").StaticFile;
module.exports.StaticFileStrict = require("./staticfile").StaticFileStrict;
module.exports.CompressorLess = require("./compressor").CompressorLess;
module.exports.CompressorJS = require("./compressor").CompressorJS;
module.exports.Cookies = require("./cookies").Cookies;
module.exports.SignedCookies = require("./cookies").SignedCookies;
module.exports.Session = require("./session").Session;
module.exports.SignedSession = require("./session").SignedSession;
module.exports.Connect = require("./connect").Connect;
module.exports.Query = require("./query").Query;
module.exports.Limiter = require("./limiter").Limiter;
module.exports.Profiler = require("./profiler").Profiler;
module.exports.BodySimple = require("./body").BodySimple;
module.exports.BodyJSON = require("./body").BodyJSON;
module.exports.BodyComplex = require("./body").BodyComplex;
module.exports.FavIcon = require("./favicon").FavIcon;
module.exports.Activity = require("./activity").Activity;
